// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvZtU7CeA2kLxptUOSEfdb82VRXXmBUhQ',
    appId: '1:1096612392773:web:91b75ed8bdecca3675582c',
    messagingSenderId: '1096612392773',
    projectId: 'practiceproject-d12b9',
    authDomain: 'practiceproject-d12b9.firebaseapp.com',
    storageBucket: 'practiceproject-d12b9.appspot.com',
    measurementId: 'G-FER7KWFR6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC98mkJcl7n7NYxplGJqd2qZdACMbzlX3E',
    appId: '1:1096612392773:android:cce3cbd9178aa8a775582c',
    messagingSenderId: '1096612392773',
    projectId: 'practiceproject-d12b9',
    storageBucket: 'practiceproject-d12b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWnDyV9i0exkmNBvEy7Js_9JPzdkuqT4Y',
    appId: '1:1096612392773:ios:0d1c5fa9cbc9a35975582c',
    messagingSenderId: '1096612392773',
    projectId: 'practiceproject-d12b9',
    storageBucket: 'practiceproject-d12b9.appspot.com',
    iosBundleId: 'com.example.practiceproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWnDyV9i0exkmNBvEy7Js_9JPzdkuqT4Y',
    appId: '1:1096612392773:ios:6880b05fa78cfc3a75582c',
    messagingSenderId: '1096612392773',
    projectId: 'practiceproject-d12b9',
    storageBucket: 'practiceproject-d12b9.appspot.com',
    iosBundleId: 'com.example.practiceproject.RunnerTests',
  );
}
